export const RUMINATE_NOTE = Symbol("RUMINATE NOTE");
export const RUMINATE_NOTE_BODY = Symbol("RUMINATE NOTE BODY");
export const RUMINATE_NOTES = Symbol("RUMINATE NOTES");
export const RUMINATE_SYNC_RATE = Symbol("RUMINATE SYNC RATE");
export const RUMINATE_SYNC_INTERVAL_REF = Symbol("RUMINATE SYNC INTERVAL REF");
export const RUMINATE_SERVER = Symbol("RUMINATE SERVER");
export const RUMINATE_UPDATE_QUEUE = Symbol("RUMINATE UPDATE");
export const RUMINATE_UPDATE_QUEUE_ALERT = Symbol("RUMINATE UPDATE QUEUE ALERT");
export const RUMINATE_NOTE_UPDATE = Symbol("RUMINATE NOTE UPDATE FUNCTION");
export const RUMINATE_REFERENCE = Symbol("RUMINATE REFERENCE");
export const RUMINATE_NOTE_SYNC = Symbol("RUMINATE NOTE SYNC");
export const RUMINATE_NOTE_PREPARE_FOR_SERVER = Symbol("RUMINATE NOTE PREPARE FOR SERVER");
export const RUMINATE_NOTE_SYNC_LIST = Symbol("RUMINATE NOTE SYNC LIST");
export const RUMINATE_NOTE_TAGS = Symbol("RUMINATE NOTE TAGS");
export const RUMINATE_NOTE_NEED_UPDATE = Symbol("RUMINATE NOTE NEED UPDATE");
export const RUMINATE_NOTE_SYNC_CR_DATA = Symbol("RUMINATE SYNCHRONIZE NOTE CR DATA");


