export const RUMINATE_NOTE = Symbol("GRAZE NOTE");
export const RUMINATE_NOTE_BODY = Symbol("GRAZE NOTE BODY");
export const RUMINATE_NOTES = Symbol("GRAZE NOTES");
export const RUMINATE_SYNC_RATE = Symbol("GRAZE SYNC RATE");
export const RUMINATE_SYNC_INTERVAL_REF = Symbol("GRAZE SYNC INTERVAL REF");
export const RUMINATE_SERVER = Symbol("GRAZE SERVER");
export const RUMINATE_UPDATE_QUEUE = Symbol("GRAZE UPDATE");
export const RUMINATE_UPDATE_QUEUE_ALERT = Symbol("GRAZE UPDATE QUEUE ALERT");
export const RUMINATE_NOTE_UPDATE = Symbol("GRAZE NOTE UPDATE FUNCTION");
export const RUMINATE_REFERENCE = Symbol("GRAZE REFERENCE")
export const RUMINATE_NOTE_SYNC = Symbol("GRAZE NOTE SYNC")
export const RUMINATE_NOTE_PREPARE_FOR_SERVER = Symbol("GRAZE NOTE PREPARE FOR SERVER")
export const RUMINATE_NOTE_SYNC_LIST = Symbol("GRAZE NOTE SYNC LIST")
export const RUMINATE_NOTE_TAGS = Symbol("GRAZE NOTE TAGS")
export const RUMINATE_NOTE_NEED_UPDATE = Symbol("GRAZE NOTE NEED UPDATE")


