.PHONY: clean All

All:
	@echo "----------Building project:[ ruminate_base - Debug ]----------"
	@cd "ruminate_base" && "$(MAKE)" -f  "ruminate_base.mk"
clean:
	@echo "----------Cleaning project:[ ruminate_base - Debug ]----------"
	@cd "ruminate_base" && "$(MAKE)" -f  "ruminate_base.mk" clean
