#include "./gnql_cpp.h" 
 

using namespace HC_TEMP;

 template <class Allocator, class NodeFunctions>
const ErrorAction Data<Allocator, NodeFunctions>::error_actions[] = {&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e,&e};

 template <class Allocator, class NodeFunctions>
const int * Data<Allocator, NodeFunctions>::goto_lookup[] = {gt1,gt2,gt2,gt3,gt4,gt2,gt5,gt6,gt7,gt2,gt2,gt2,gt2,gt2,gt8,gt2,gt2,gt2,gt2,gt9,gt2,gt2,gt2,gt2,gt2,gt10,gt2,gt2,gt2,gt2,gt2,gt11,gt2,gt2,gt12,gt7,gt7,gt2,gt2,gt2,gt13,gt14,gt2,gt2,gt2,gt15,gt2,gt2,gt2,gt2,gt2,gt16,gt17,gt18,gt19,gt20,gt2,gt7,gt2,gt21,gt22,gt2,gt2,gt2,gt2,gt23,gt2,gt2,gt24,gt2,gt2,gt25,gt2,gt2,gt26,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt7,gt2,gt2,gt27,gt2,gt28,gt29,gt30,gt31,gt32,gt33,gt34,gt35,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt36,gt2,gt37,gt38,gt39,gt40,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt41,gt2,gt42,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt43,gt2,gt44,gt2,gt2,gt45,gt46,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt7,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt2,gt47,gt48,gt2,gt2,gt2,gt2,gt49,gt2,gt2,gt2,gt2,gt2,gt50,gt2,gt2,gt2,gt2,gt2,gt2,gt51,gt2,gt2,gt2,gt2,gt2,gt2,gt2};

 template <class Allocator, class NodeFunctions>
const int * Data<Allocator, NodeFunctions>::state_lookup[] = {sm0,sm1,sm2,sm3,sm4,sm5,sm6,sm7,sm8,sm9,sm10,sm11,sm11,sm12,sm13,sm14,sm14,sm14,sm14,sm15,sm16,sm17,sm18,sm19,sm20,sm21,sm22,sm23,sm24,sm25,sm26,sm27,sm28,sm29,sm30,sm31,sm32,sm33,sm34,sm35,sm36,sm37,sm38,sm38,sm38,sm39,sm40,sm41,sm42,sm43,sm44,sm45,sm45,sm45,sm45,sm21,sm46,sm47,sm46,sm39,sm39,sm48,sm48,sm48,sm48,sm49,sm50,sm50,sm51,sm52,sm52,sm53,sm54,sm54,sm55,sm56,sm56,sm56,sm56,sm57,sm58,sm59,sm59,sm59,sm59,sm60,sm61,sm62,sm62,sm63,sm64,sm65,sm65,sm65,sm65,sm65,sm65,sm65,sm65,sm66,sm66,sm66,sm66,sm67,sm68,sm69,sm70,sm71,sm72,sm73,sm73,sm74,sm75,sm75,sm76,sm76,sm77,sm78,sm79,sm80,sm81,sm73,sm82,sm83,sm84,sm84,sm85,sm86,sm87,sm87,sm87,sm87,sm87,sm88,sm88,sm88,sm88,sm88,sm89,sm90,sm91,sm79,sm81,sm92,sm21,sm93,sm94,sm94,sm94,sm94,sm95,sm95,sm95,sm95,sm96,sm97,sm97,sm98,sm87,sm88,sm99,sm100,sm101,sm102,sm103,sm104,sm104,sm105,sm106,sm107,sm108,sm109,sm110,sm110,sm111,sm112,sm113,sm114,sm115,sm116,sm117,sm118,sm73,sm119,sm119,sm119,sm119,sm119,sm120,sm83,sm121,sm121,sm121,sm121,sm122,sm123,sm124};

 template <class Allocator, class NodeFunctions>
const wstring Data<Allocator, NodeFunctions>::tk_symbols[] = {L"&&",L"||"};

 template <class Allocator, class NodeFunctions>
const SymbolLookup Data<Allocator, NodeFunctions>::symbol_lu = {{wstring(1, (wchar_t) 15728641),1},
{wstring(1, (wchar_t) 15728642),2},
{wstring(1, (wchar_t) 15728644),3},
{wstring(1, (wchar_t) 15728648),4},
{wstring(1, (wchar_t) 15728656),5},
{wstring(1, (wchar_t) 15728672),6},
{wstring(1, (wchar_t) 15728704),7},
{wstring(1, (wchar_t) 15728768),8},
{wstring(1, (wchar_t) 15728896),9},
{wstring(1, (wchar_t) 15729152),10},
{wstring(1, (wchar_t) 15728643),11},
{wstring(1, (wchar_t) 15728904),12},
{wstring(1, (wchar_t) 15728840),13},
{wstring(1, (wchar_t) 15728841),14},
{L"/",15},
{L"?",16},
{L":",17},
{L"f",18},
{L"filter",19},
{L"Filter",20},
{L"FILTER",21},
{L"&&",22},
{L"AND",23},
{L"And",24},
{L"and",25},
{L"||",26},
{L"OR",27},
{L"Or",28},
{L"or",29},
{L"NOT",30},
{L"Not",31},
{L"not",32},
{L"!",33},
{L"(",34},
{L")",35},
{L"|",36},
{L"s",37},
{L"sort",38},
{L"SORT",39},
{L"Sort",40},
{L",",41},
{L"created",42},
{L"CREATED",43},
{L"modifier",44},
{L"MODIFIED",45},
{L"size",46},
{L"SIZE",47},
{L"#",48},
{L"is",49},
{L"equals",50},
{L"=",51},
{L"that",52},
{L"greater",53},
{L"than",54},
{L">",55},
{L"less",56},
{L"<",57},
{L"lesser",58},
{L"from",59},
{L"to",60},
{L"-",61},
{L"TO",62},
{L"To",63},
{L"through",64},
{L"on",65},
{L"date",66},
{L"DES",67},
{L"des",68},
{L"descending",69},
{L"DESCENDING",70},
{L"down",71},
{L"ASC",72},
{L"asc",73},
{L"ascending",74},
{L"ASCENDING",75},
{L"up",76},
{L"\"",77},
{L"'",78},
{L"*",79},
{L"│",80},
{L"\\",81}};

template <class Allocator, class NodeFunctions>
int (* const Data<Allocator, NodeFunctions>::state_actions[])(Token&, int&, void **, void*) = {[](Token& tk, int& output_offset, void ** output, void * alloc)->int{(reduceToNull(0, output_offset, output)); return 2051;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 74;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 70;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 66;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 62;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 26;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 82;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 86;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 90;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 94;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 98;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 106;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 110;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 114;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 118;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 122;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 54;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 5;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 1031;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::QueryBody, 1, alloc); return 2055;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::QueryBody, 2, alloc); return 2055;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::QueryBody, 4, alloc); return 2055;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::ContainerClause, 1, alloc); return 3079;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::ContainerClause, 2, alloc); return 3079;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::ContainerClause, 4, alloc); return 3079;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 154;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::ContainerIdentifierList, 1, alloc); return 4103;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::Identifier, 1, alloc); return 40967;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 41991;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 45063;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::StringData, 1, alloc); return 44039;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 186;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 166;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 182;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::SYMBOL, 1, alloc); return 49159;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::FilterClause, 1, alloc); return 7175;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 206;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 210;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 214;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 218;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 222;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 266;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 270;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 278;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 282;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 290;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 294;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 298;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 238;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 242;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 6151;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 302;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 306;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 310;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 314;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 13319;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 326;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 330;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 334;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 338;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::QueryBody, 3, alloc); return 2059;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::QueryBody, 5, alloc); return 2059;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::QueryBody, 6, alloc); return 2059;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ContainerClause, 3, alloc); return 3083;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ContainerClause, 5, alloc); return 3083;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ContainerClause, 6, alloc); return 3083;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ContainerIdentifierList, 3, alloc); return 4107;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ContainerIdentifier, 3, alloc); return 5131;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::Identifier, 3, alloc); return 40971;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::StringData, 3, alloc); return 44043;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::StringDataVal, 1, alloc); return 46087;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::SYMBOL, 1, alloc); return 48135;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::FilterClause, 3, alloc); return 7179;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 9223;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 366;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 370;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 374;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 378;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 10247;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 382;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 386;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 390;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 394;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 11271;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 12295;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 16391;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::CreatedStatement, 1, alloc); return 18439;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 446;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 458;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 462;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 466;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 474;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 470;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 478;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 482;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 490;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 498;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 502;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 514;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 518;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 522;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 526;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 530;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 534;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 538;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 542;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 546;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 550;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 17415;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::ModifiedStatement, 1, alloc); return 20487;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 19463;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 566;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 570;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 21511;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 6155;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::SortClause, 3, alloc); return 14347;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 578;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::SortStatementList, 1, alloc); return 15367;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 13323;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::QueryBody, 7, alloc); return 2063;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::ContainerClause, 7, alloc); return 3087;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::StringDataVal, 3, alloc); return 46091;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::EscapedValue, 3, alloc); return 47115;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::NotNode, 3, alloc); return 11275;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 618;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 622;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 626;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::CreatedStatement, 3, alloc); return 18443;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 634;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 638;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::CreatedStatement, 5, alloc); return 18443;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 650;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 24583;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 670;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 674;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::LAST, 2, alloc); return 27655;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 678;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 37895;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 25607;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 38919;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 26631;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 28679;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 32775;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::OrderDescending, 1, alloc); return 39943;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::OrderAscending, 1, alloc); return 39943;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ModifiedStatement, 3, alloc); return 20491;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ModifiedStatement, 5, alloc); return 20491;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::SizeStatement, 3, alloc); return 22539;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::TagStatement, 3, alloc); return 23563;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::StringDataVal, 7, alloc); return 46095;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::AndNode, 7, alloc); return 9231;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::OrNode, 7, alloc); return 10255;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::WrappedExpression, 7, alloc); return 12303;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::Sentence, 7, alloc); return 43023;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::CreatedStatement, 7, alloc); return 18447;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ComparisonExpressionEquals, 3, alloc); return 27659;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,1,&NodeFunctions::NUMBER, 1, alloc); return 50183;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ComparisonExpressionMore, 3, alloc); return 27659;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::ComparisonExpressionLess, 3, alloc); return 27659;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::LAST, 3, alloc); return 27659;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 25611;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 718;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 26635;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 722;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 24587;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::RangeExpression, 3, alloc); return 31755;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 734;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 738;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 742;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 746;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 750;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,2,&NodeFunctions::DateExpression, 3, alloc); return 36875;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 762;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 766;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 770;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{; return 774;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 33799;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::ModifiedStatement, 7, alloc); return 20495;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::SizeStatement, 7, alloc); return 22543;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::TagStatement, 7, alloc); return 23567;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::TagStatement, 11, alloc); return 23567;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::SortStatementList, 7, alloc); return 15375;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(3, output_offset, output); return 25615;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(3, output_offset, output); return 26639;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::RangeExpression, 7, alloc); return 31759;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 29703;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,3,&NodeFunctions::DateExpression, 7, alloc); return 36879;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(1, output_offset, output); return 34823;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToValue(tk,output_offset,output,4,&NodeFunctions::TagStatement, 15, alloc); return 23571;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 30731;},
[](Token& tk, int& output_offset, void ** output, void * alloc)->int{reduceToNull(2, output_offset, output); return 35851;}};

